name: Test case

on:
  push:
    paths:
      - 'test/**'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: Test 
      run: 
        make -C test
